// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARDYTU5oNHeSHIdtaWbuWBK8vysxOLDXU',
    appId: '1:752846935485:web:28a85cb2371c4c28f16ed4',
    messagingSenderId: '752846935485',
    projectId: 'flutter-8dc0a',
    authDomain: 'flutter-8dc0a.firebaseapp.com',
    storageBucket: 'flutter-8dc0a.appspot.com',
    measurementId: 'G-S5GJL20X5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPWO74pFXmrrSnga8vQ4atyI7M_XRPLjk',
    appId: '1:752846935485:android:65046e52092f7990f16ed4',
    messagingSenderId: '752846935485',
    projectId: 'flutter-8dc0a',
    storageBucket: 'flutter-8dc0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG1O6stfTZE-1rIlkTh1IIZxpojLqpuWA',
    appId: '1:752846935485:ios:ba7333f65bd124c9f16ed4',
    messagingSenderId: '752846935485',
    projectId: 'flutter-8dc0a',
    storageBucket: 'flutter-8dc0a.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
